//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Course.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class Course {
	public String name;
	public ArrayList<String> materials;
	public ArrayList<Student> students;
	public Professor professor;
	public Map<String, Grade> grades;
	private String password;
	
	public Course(String name, String password, Professor professor) {
		this.password = password;
		this.name = name;
		this.professor = professor;
		materials = new ArrayList<>();
		students = new ArrayList<>();
		grades = new HashMap<String,Grade>();
	}

	String getPassword(){
		return password;
	}
}
