//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Department.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;

public class Department {
	public ArrayList<Professor> profesors;
	public String name;
	public Professor getProfessor(String index, String password) {
		int size = profesors.size();
		for(int i = 0; i < size; ++i){
			if(profesors.get(i).authenticate(password, index) == true){
				return profesors.get(i);
			}
		}
		return null;	 // placehodler
	}
	
	public Department(String name) {
		this.name = name;
		profesors = new ArrayList<Professor>();
	}
	
	public User addTeacher(String fullName, String password, int index) {
		Professor newProfessor = new Professor(fullName, password, index, this);
		profesors.add(newProfessor);

		return newProfessor;
	}
}
