//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Department.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;

public class Department {
	public ArrayList<Professor> profesors;
	public String name;
	public Professor getProfessor(String index, String password) {
		return null;
	}
	
	public Department(String name) {
		this.name = name;
	}
	
	public void addTeacher(String fullName, String password, String index) {
	
	}
}
