//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Professor.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;
import java.io.File;

public class Professor extends User {
	public ArrayList<Course> courses;
	public Department department;

	public void addCourse(String name, String password) {
		for(Course course: courses){
			if(course.name.equals(name)){
				System.out.println("Such course already exists!");
				return;
			}
		}
		Course newCourse = new Course(name, password, this);
		courses.add(newCourse);
	}
	
	public void addMaterials(String nameOfFile, Course course) {
		File file = new File(nameOfFile);
        boolean exists = file.exists();
        
        if (!exists) {
            System.out.println("Such file does not exist.");
        }
		for(String tmp: course.materials){
			if(tmp == nameOfFile){
				System.out.println("Such file already exists!");
				return;
			}
		}
		course.materials.add(nameOfFile);
	}
	
	public void writeGrade(String index, Grade grade, Course course) {
		if(!courses.contains(course)){
			System.out.println("Professor doesn't have such course!");
			return;
		}
		boolean isStudentRegistered = false;
		for(Student student: course.students){
			if(student.getIndex() == index){
				isStudentRegistered = true;
				break;
			}
		}
		if(isStudentRegistered){
			course.grades.put(index, grade);
		}else{
			System.out.println("Such student isn't registered on this course!");
		}
	}
	
	public Professor(String fullName, String password, String index, Department department) {
		super(fullName, password, index);
		this.department  = department;
		this.courses = new ArrayList<Course>();
		this.courses = new ArrayList<>();
	}
}
//studia nie sa obowiazkowe
