//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Professor.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;

public class Professor extends User {
	public ArrayList<Course> courses;
	public Department department;
	public void addCourse(String name, String password) {
	
	}
	
	public void addMaterials(String nameOfFile, String nameOfCourse) {
	
	}
	
	public void writeGrade(String index, Grade grade) {
	
	}
	
	public Professor(String fullName, String password, String index, Department department) {
		super(fullName, password, index);
		this.department  = department;
	}
}
//studia nie sa obowiazkowe
