//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;

public class Student extends User {
	public ArrayList<Course> classes;
	public University university;
	public void registerOnCourse(String nameOfCourse, String nameOfDepartment, Professor professor, String password) {
	
	}
	
	public void viewGrades() {
	
	}
	
	public void viewMaterial(String course, String nameOfFile) {
	
	}
	
	public void Student(String fullName, String passwrod, String index, University university) {
	
	}
}
//pozdrwaiam ciebie