//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : University.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;

public class University {
	public ArrayList<Department> departments;
	public ArrayList<Student> students;
	public String name;
	public boolean reg(boolean isTeacher, String fullName, String password, String index, Department department) {
		
		return true;
	}
	
	public User logIn(boolean isTeacher, String password, String index, String departmentName) {
		
		return null;
	}
	
	public Student getStudent(String index, String password) {
		return null;
	}
	
	public University(String name) {
        this.name = name;
        departments = new ArrayList<Department>();

        // Create Department objects
        Department department1 = new Department("Mathematics");
        Department department2 = new Department("Computer Science");
        Department department3 = new Department("Physics");
		Department department4 = new Department("Neurobiology");
		Department department5 = new Department("cosmology");

        // Add Department objects to departments ArrayList
        departments.add(department1);
        departments.add(department2);
        departments.add(department3);
		departments.add(department4);
		departments.add(department5);
    }
}
