//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : University.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;

public class University {
	public ArrayList<Department> departments;
	public ArrayList<Student> students;
	public String name;
	public boolean reg(boolean isTeacher, String fullName, String password, String index, Department department) {
		
		return true;
	}
	
	public User logIn(boolean isTeacher, String password, String index, String departmentName) {
		
		return null;
	}
	
	public Student getStudent(String index, String password) {
		return null;
	}
	
	public University(String name) {
		
	}
}
