//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//




public abstract class User {
	private String fullName;
	private String password;
	private int index;
	public boolean authenticate(String password, String index) {
		return false;
	}
	public User(String fullName, String password, int index){
		this.fullName = fullName;
		this.password = password;
		this.index = index;
	}

	public int getIndex() {
		return index;
	}

	public String getPassword() {
		return password;
	}
}
