//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 20.05.2024
//  @ Author : 
//
//




public abstract class User {
	private String fullName;
	private String password;
	private String index;
	public boolean authenticate(String password, String index) {
		if(this.index == index && this.password == password)
			return true;
		return false;
	}
	public User(String fullName, String password, String index){
		this.fullName = fullName;
		this.password = password;
		this.index = index;
	}

	public String getIndex() {
		return index;
	}

	public String getPassword(){
		return password;
	}

	public String getFullName(){
		return fullName;
	}
}
