//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Course.java
//  @ Date : 21.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class Course {
	public String name;
	public ArrayList<String> materials;
	public ArrayList<Student> students;
	public Professor professor;
	public Map<Integer, Grade> grades;
	private String password;

	public Course(String name, Professor professor, String password) {
		this.password = password;
		this.name = name;
		this.professor = professor;
		materials = new ArrayList<>();
		students = new ArrayList<>();
		grades = new HashMap<Integer, Grade>();
	}
	
	public String getPassword(){
		return password;
	}
}
