//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Professor.java
//  @ Date : 21.05.2024
//  @ Author : 
//
//

import java.io.File;
import java.util.ArrayList;

public class Professor extends User {
	public ArrayList<Course> courses;
	public Department department;

	public String addCourse(String name, String password) {
		for(Course course: courses){
			if(course.name.equals(name)){
				return"Such course already exists!";
			}
		}
		Course newCourse = new Course(name, this, password);
		courses.add(newCourse);
		return "New course was added";
	}
	
	public String addMaterials(String nameOfFile, Course course) {
		File file = new File(nameOfFile);
        boolean exists = file.exists();
		if(courses.contains(course) == false){
			return "Such a course does not belongs to professor!";
		}
        if (!exists) {
            return "Such file does not exist.";
        }
		return course.addMaterialToCourse(nameOfFile);
	}
	
	public String writeGrade(int index, Grade grade, Course course) {
		if(!courses.contains(course)){
			return "Professor doesn't have such course!";
		}
		return course.addGradeToStudent(index, grade);
	}
	
	public Professor(String fullName, String password, int index, Department department) {
		super(fullName, password, index);
		this.department = department;
		courses = new ArrayList<>();
	}
}
