//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 21.05.2024
//  @ Author : 
//
//


import java.util.ArrayList;

public class Student extends User {
	public ArrayList<Course> courses;
	public University university;

	public String registerOnCourse(Course course, String password) {
		if(courses.contains(course)){
				return "You are already registered on this course!";
		}
		if (course.getPassword().equals(password)) {
			courses.add(course);
			course.students.add(this);
			return "Student registered on course " + course.name;
		} else {
			return "Wrong password for course " + course.name;
		}
	}
	 
	public String viewGrades() {
		StringBuilder stringBuilder = new StringBuilder();
		boolean studentFound = false;
		int index = this.getIndex();
		for (Course course : courses) {
			Grade grade = course.getGrade(index);

			if (grade != null) {
				studentFound = true;
				stringBuilder.append("Course: ").append(course.name)
						.append(" - Grade: ").append(grade.name()).append("\n");
			}
		}

		if (!studentFound) {
			stringBuilder.append("No grade found for student with ID: ").append(this.getIndex()).append("\n");
		}
		return stringBuilder.toString();
	}
	
	public String viewMaterial(Course course, String nameOfFile) {
		if(courses.contains(course) == false){
			return "Student isn't registered on such course!";
		}
		return course.openFile(nameOfFile);
	}
	
	public Student(String fullName, String password, int index, University university) {
		super(fullName, password, index);
		this.university = university;
		courses = new ArrayList<>();
	}
}
