//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 21.05.2024
//  @ Author : 
//
//

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.awt.Desktop;

public class Student extends User {
	public ArrayList<Course> courses;
	public University university;
	public String registerOnCourse(Course course, String password) {
		if(courses.contains(course)){
				return "You are already registered on this course!";
		}
		if (course.getPassword().equals(password)) {
			courses.add(course);
			return "Student " + this.getFullName() + " registered on course " + course.name;
		} else {
			return "Wrong password for course " + course.name;
		}
	}
	
	public String viewGrades() {
		StringBuilder stringBuilder = new StringBuilder();
		boolean studentFound = false;

		for (Course course : courses) {
			Grade grade = course.grades.get(this.getIndex());

			if (grade != null) {
				studentFound = true;
				stringBuilder.append("Course: ").append(course.name)
						.append(" - Grade: ").append(grade.name()).append("\n");
			}
		}

		if (!studentFound) {
			stringBuilder.append("No grade found for student with ID: ").append(this.getIndex()).append("\n");
		}
		return stringBuilder.toString();
	}
	
	public String viewMaterial(Course course, String nameOfFile) {
		if(courses.contains(course) == false){
			return "Student isn't registered on such course!";
		}
		String message = null;
			if (course.materials.contains(nameOfFile) == false){
				message =  "There is no such file";
			}
			else {
				File file = new File(nameOfFile);

        
        		if (!Desktop.isDesktopSupported()) {
					message = "Desktop is not supported on this system.";
      	    	}

       			Desktop desktop = Desktop.getDesktop();

        		try {
            		if (file.exists()) {
                		desktop.open(file);
            		} else {
						message = "File does not exist: ";
            		}
        		} catch (IOException e) {
            		message = "An error occurred while opening the file: " + e.getMessage();
        		}
			}
			return message;
	}
	
	public Student(String fullName, String password, int index, University university) {
		super(fullName, password, index);
		this.university = university;
		courses = new ArrayList<>();
	}
}
