//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : University.java
//  @ Date : 21.05.2024
//  @ Author : 
//
//

import java.util.ArrayList;

public class University {
	public ArrayList<Department> departments;
	public ArrayList<Student> students;
	public String name;
	private int indexGenerator;

	public String regStudent(String fullName, String password) {
		Student student = new Student(fullName, password, indexGenerator, this);
		students.add(student);
		String ret = "Your index is " + indexGenerator + ". Remember it!";
		++indexGenerator;
		return ret;
	}
	
	public Professor logInProfessor(int index, String password) {
		for (Department department: departments) {
			Professor professor = department.getProfessor(index, password);
			if (professor != null) {
				return professor;
			}
		}
		return null;
	}
	
	public University(String name, int startingIndex) {
		this.name = name;
        departments = new ArrayList<Department>();
		students = new ArrayList<>();
		this.indexGenerator = startingIndex;
	}
	
	public String regProfessor(String fullName, String password, Department department) {
		if(departments.contains(department) == false){
			return "There is no such department fot this university!";
		}
		department.addProfessor(fullName, password, indexGenerator);
		String ret = "Your index is " + indexGenerator + ". Remember it!";
		++indexGenerator;
		return ret;
	}
	
	public Student logInStudent(int index, String password) {
		for(Student student: students) {
			if(student.authenticate(index, password)){
				return student;
			}
		}
		return null;
	}

	public void addDepartment(String name){
		Department dept = new Department(name);
		departments.add(dept);
	}
}
