//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 21.05.2024
//  @ Author : 
//
//




public abstract class User {
	private String fullName;
	private String password;
	private int index;
	public boolean authenticate(int index, String password) {
		if(this.index == index && this.password.equals(password)){
			return true;
		}
		return false;
	}
	
	public int getIndex() {
		return index;
	}
	
	public String getFullName() {
		return fullName;
	}

	public User(String fullName, String password, int index){
		this.password = password;
		this.fullName = fullName;
		this.index = index;
	}
}
